### ISSUE TITLE
wp-scss Doesn't work

### ISSUE THREAD

**Issue by EleanorEllis** [ConnectThink/WP-SCSS#56]
This plugin doesn't appear to work at all. No css files appear in my css directory. No error messages appear on screen. The only file that gets created is _stylesheets/csscssload_partial_stylesheets.css_ which is an empty file (0 bytes). I also notice that functions.php has not been updated to enqueue anything.

I have also tried updating phpscss as suggested in [https://github.com/ConnectThink/WP-SCSS/issues/39](https://github.com/ConnectThink/WP-SCSS/issues/39)
The method I used to try to update phpscss was as follows:
1. Deactivate wp-scss
2. Rename /wp-content/plugins/wp-scss/scssphp to old-scssphp
3. Create new scssphp directory
4. Copy contents of update into new scssphp directory so that 
5. Activate wp-scss

This didn't make any difference.

My settings are as follows:
![image](https://cloud.githubusercontent.com/assets/7861502/14370474/5e948144-fd26-11e5-998a-771a3be20174.png)

My theme is Divi from elegantthemes.com and I am using a Child Theme created by [https://wordpress.org/plugins/child-theme-configurator/](https://wordpress.org/plugins/child-theme-configurator/)

My directory tree underneath _/wp-content/themes/Divi-child_ is as follows:
![divi-child directory tree](https://cloud.githubusercontent.com/assets/7861502/14371641/a7888d40-fd31-11e5-9836-14df20ce5147.png)

I am attaching my files so hopefully you can rule out errors in my scss files.

**Divi-child/styles.css**

/*
Theme Name: Divi Child
Theme URI: http://www.elegantthemes.com/gallery/divi/
Template: Divi
Author: Elegant Themes
Author URI: http://www.elegantthemes.com
Description: Smart. Flexible. Beautiful. Divi is the most powerful theme in our collection.
Tags: responsive-layout,one-column,two-columns,three-columns,four-columns,left-sidebar,right-sidebar,custom-background,custom-colors,featured-images,full-width-template,post-formats,rtl-language-support,theme-options,threaded-comments,translation-ready
Version: 2.7.1.1460076929
Updated: 2016-04-08 00:55:29

*/

--- End of file ---

**Divi-child/functions.php**

<?php // Opening PHP tag - nothing should be before this, not even whitespace
// Exit if accessed directly
if ( !defined( 'ABSPATH' ) ) exit;

// BEGIN ENQUEUE PARENT ACTION
// AUTO GENERATED - Do not modify or remove comment markers above or below:

if ( !function_exists( 'chld_thm_cfg_parent_css' ) ):
    function chld_thm_cfg_parent_css() {
        wp_enqueue_style( 'chld_thm_cfg_parent', trailingslashit( get_template_directory_uri() ) . 'style.css', array(  ) );
    }
endif;
add_action( 'wp_enqueue_scripts', 'chld_thm_cfg_parent_css', 10 );

// END ENQUEUE PARENT ACTION

/**
- Requires Event Organiser 1.6+
  *
- Adds the venue's name to the content appearing in the tooltip when hovering over an event in fullcalendar
- @uses eventorganiser_event_tooltip filter.
  *
- The filter passes 4 objects: the content of the toolip, the post ID of the event, the occurrence ID 
- of the event and the post object (the last one probably won't often bed needed).
- In this example we just need the first two.
  */

// As of 4 March 2016 this doesn't work. This code came from https://gist.github.com/stephenh1988/4040699
add_filter('eventorganiser_event_tooltip', 'my_event_tooltip_content', 10,2);
function my_event_tooltip_content( $description, $post_id ){

```
$venue_id = eo_get_venue($post_id);

if(  $venue_id ){
            //Event has a venue, append this to the event description.
    $description = 'This event is at '.eo_get_venue_name($venue_id).'</br></br>'.$description;

}

return $description;
```

}

--- End of file ---

// load_partial_stylesheets.scss
// Eleanor Ellis 7 April 2016 @ 20-51

@import "_variables.scss"
@import "_colours.scss"
@import "_mixins.scss"
@import "//cdn-images.mailchimp.com/embedcode/classic-10_7.css"
@import "_page_and_post_default_styling.scss"
@import "_elements_in_pages_and_posts_default_styling.scss"
@import "_elements_in_pages_and_posts_user_generated.scss"
@import "_mailchimp.scss"

--- End of file ---

// _variables.scss
// Eleanor Ellis 7 April 2016

// Colours
$pdc-pink: #c37cc6;
$pdc-pink-transparent: rgba(195, 124, 198, 0.7);
$smoked-glass-fallback: rgb(7, 7, 7);
$smoked-glass: rgba(10, 10, 10, 0.7);

// Default params
$border-radius-default: 25px;
$box-shadow-default: 10px 10px 5px rgba(0,0,0,0.5);
$border-default: 2px solid;

// Other params
$button-shadow: 0px 6px 0px #2b638f, 
                0px 3px 15px rgba(0,0,0,.4), 
                inset 0px 1px 0px rgba(255,255,255,.3), 
                inset 0px 0px 3px rgba(255,255,255,.5);

$button-shadow-active:  0px 2px 0px #2b638f, 
                        0px 1px 6px rgba(0,0,0,.4), 
                        inset 0px 1px 0px rgba(255,255,255,.3), 
                        inset 0px 0px 3px rgba(255,255,255,.5);

$button-translation-active: 0, 4px;
$button-transition-active: all .2s ease-in-out;

$margin-default: 20px;

--- End of file ---

// _colours.scss

.pdc-pink-background {
    background: $pdc-pink;
}

.pdc-pink-transparent-background {
    background: $pdc-pink-transparent;
}

.smoked-glass-background {
    background: $smoked-glass-fallback;
    background: $smoked-glass;
}

.post {
    a {
        color: #EDB059 !important;
    }
}

--- End of file ---

// _mixins.scss
// Eleanor Ellis 7 April 2016

@mixin border-radius($radius) {
  -webkit-border-radius: $radius;
     -moz-border-radius: $radius;
      -ms-border-radius: $radius;
          border-radius: $radius;
}

@mixin text-shadow($params) {
  -webkit-text-shadow: $params;
     -moz-text-shadow: $params;
      -ms-text-shadow: $params;
          text-shadow: $params;
}

@mixin box-shadow($params) {
  -webkit-box-shadow: $params;
     -moz-box-shadow: $params;
      -ms-box-shadow: $params;
          box-shadow: $params;
}

@mixin display-flex {
    display: -webkit-flex;
    display;    -moz-flex;
    display:     -ms-flex;
    display:         flex;
}

@mixin justify-content($params) {
    -webkit-justify-content: $params;
       -moz-justify-content: $params;
        -ms-justify-content: $params;
            justify-content: $params;
}

@mixin align-items($params) {
    -webkit-align-items: $params;
       -moz-align-items: $params;
        -ms-align-items: $params;
            align-items: $params;
}

@mixin transform($params) {
    -webkit-transform: $params;
       -moz-transform: $params;
        -ms-transform: $params;
            transform: $params;
}

@mixin transition($params) {
    -webkit-transition: $params;
       -moz-transition: $params;
        -ms-transition: $params;
            transition: $params;
}

@mixin filter($params) {
    -webkit-filter: $params;
       -moz-filter: $params;
        -ms-filter: $params;
            filter: $params;
}

--- End of file ---

// _page_and_post_default_styling.scss
// Eleanor Ellis. 7 April 2016

// This comment is to check WordPress is serving the most recent stylesheets. Eleanor Ellis 8 April 2016 @ 02-01

/\* Begin Header styling */
# top-header {

```
@include border-radius($border-radius-default $border-radius-default 0 0);
@include box-shadow($box-shadow-default);
border: $border-wdith-default;
border-bottom: none;
z-index: 10;
```

}
# et-info,
# et-secondary-menu {

```
a: link {
    color: rgba(255,255,255,0.9);
};

a: hover {
color: white;
};
```

}
# main-header {

```
margin-bottom: $margin-default;
border: $border-default;
border-top: none;
@include border-radius(0 0 $border-radius-default $border-radius-default);
@include box-shadow($box-shadow-default);
z-index: 11;
```

}

/\* End Header styling */

/\* Begin Footer styling */

/\* 
For some reason, there is still something with square corners at the top of the footer. Carry on adding elements till I find it! 
Eleanor Ellis 7 Apr 2016
*/
# main-footer {

```
margin-top: $margin-default;
```

/\*  margin-bottom: $margin-default; */
    border: $border-default;
    @include box-shadow($box-shadow-default);
}
# main-footer,
# footer-bottom,
# et-footer-nav {

```
    @include border-radius($border-radius-default);
```

}

.fc-toolbar .fc-left, 
.fc-toolbar .fc-right {
    float: left !important;
}

/\* End Footer styling */

/\* Begin Default styling for Divi sections and posts. Eleanor Ellis 31 March 2016 
See https://www.elegantthemes.com/forum/viewtopic.php?f=187&t=321471&p=1770424
*/

.single, 
.page, 
.archive {
    #main-content {
        margin-top: $margin-default;
        margin-bottom: $margin-default;
    }
}

.et_boxed_layout {
    #page-container {
    @include box-shadow(none !important);
    }
}

.et_pb_section, 
.single #main-content, 
.page #main-content, 
.archive #main-content {
    border: $border-default;
    @include border-radius($border-radius-default);
    @include box-shadow($box-shadow-default);
    background: $smoked-glass-fallback !important;
    background: $smoked-glass !important; 
    }

.et_pb_row: first-of-type {
    padding-top: 0;
    }

.archive, 
.single {
    #sidebar {
        display: none; 
    }
}

/\* Comment input field styling. This was for before the Divi builder was available for posts, but still may be useful if user doesn't choose Divi builder. Eleanor Ellis 31 March 2016 */
textarea {
    #comment {
        background-color: rgba(255,255,32,0.6) !important;
        color: black !important;
        @include box-shadow( 10px 10px 5px rgba(0,0,0,0.5) !important; )
        border: $border-default !important; 
    }
}

/\* End Default styling for Divi sections and posts */

--- End of file ---

// _elements_in_pages_and_posts_default_styling.scss
// Eleanor Ellis. 7 April 2016

img {
    margin-bottom: 10px;
    }

/\* "ET Learn more block" shortcode generated from Content Editor toolbar within most Divi modules. 
Eleanor Ellis 28 March 2016 
*/

.et-learn-more h3.heading-more {
    color: black !important;
    }

 /\* Stop sliders jumping downwards at slide transition. 
 Fix from Divi support ticket. 
 */

.et_pb_slider .et_pb_slide {
    list-style: none !important;
    }

/\* Styling for Divi toggle. No longer necessary now Divi 2 is here. 
Eleanor Ellis 31 March 2016 _/
/_
.et_pb_toggle {
    border-radius: 10px;
    border: 2px solid;
    box-shadow: 5px 5px 2.5px rgba(0,0,0,0.5) !important;
    -webkit-box-shadow: 5px 5px 2.5px rgba(0,0,0,0.5) !important;
    -moz-box-shadow: 5px 5px 2.5px rgba(0,0,0,0.5) !important;
    background: rgb(84, 21, 26) !important;
    background: rgba(84, 21, 26, 0.8) !important;
    }
*/

/\* Style the Accordion and Toggle - no longer necessary with Divi 2. 
Eleanor Ellis 31 March 2016 _/
/_
.et_pb_toggle_close h5.et_pb_toggle_title, 
.et_pb_toggle_open, 
.et_pb_toggle_open h5.et_pb_toggle_title  {
    color: white !important;
    }
 */

/\* 
Add 3D styling, hover, and animation to buttons.  
See http://designmodo.com/3d-css3-button/  
Eleanor Ellis 31 March 2016. 
*/

/\* Shadow for button in the non-active state */
.small-button, 
.big-button, 
.icon-button {
    @include box-shadow($button-shadow)
}

/\* Make brightness of non-text buttons increase on hover, same as text buttons already do */
.icon-button: hover {
    @include filter( brightness(84%) )
}

.small-button: active, 
.big-button: active, 
.icon-button: active {
    /\* When the button is pressed, we need to rework both of the shadows that come out from the button. Our solid bottom shadow needs to shorten so that the button looks pressed. Then the blurred shadow needs to become smaller, since a shorter button would cast a smaller shadow. */
    @include box-shadow($button-shadow-active);

```
/* We also need to move the button down by the same number of pixels that we shortened our shadow (in this case 4px). Otherwise, it will look like the shadow got shorter rather than the button being pressed down. */
@include transform( translate($button-translation-active) );

/* Automatically animate both our box shadows and the transform position. That’s the “all” keyword. The .2s means that I want the entire animation to take .2 seconds. And finally ease-in-out refers to the timing of the animation. Now the button presses down smoothly and animates back up when you release your mouse. And of course the browsers that don’t support it won’t know what they are missing. */
@include transition($button-transition-active);
```

}
/\* End of Add 3D styling, hover, and animation to buttons */

--- End of file ---

// _elements_in_pages_and_posts_user_generated.scss
// Eleanor Ellis. 7 April 2016

.rounded {
    @include border-radius($border-radius-default)
}

.shadow {
    @include box-shadow($box-shadow-default)
}

.solid-border {
    border: $border-wdith-default solid;
}

/\* 
Begin .LeftCentreRightContainer (distributes items to left, centre, and right of container). For those browsers that do not support CSS3 FlexBox, falls back to aligning elements in a line from left edge of container. 
Eleanor Ellis 31 March 2016 
*/

.LeftCenterRightContainer {
    @include display-flex;
    @include justify-content(space-between);
    @include align-items(center);
    }

.LeftCenterRightContainer > \* {
    display: inline-block; 
    vertical-align: middle;
    }

/\* End .LeftCentreRightContainer */

--- End of file ---

// _mailchimp.scss
// Eleanor Ellis. 7 April 2016

/\* Suggested default styling from embedded form generator _/
/_ MailChimp's stylesheet is enqueued by WP-SCSS */
# mc_embed_signup {

```
    background: transparent; 
```

/\*      clear:left; 
        font:14px Helvetica,Arial,sans-serif;   */
        }

/\* End Suggested default styling from embedded form generator */

/*
Align MailChimp form items with Divi modules. 
Eleanor Ellis 28 March 2016 
*/
# mc_embed_signup form {

```
padding: 24px 30px; 
}
```
# mc_embed_signup_scroll .mc-field-group,
# mc_embed_signup .indicates-required {

```
margin: 0;
width: 100%;
}
```
# OrganiserSignUpTerms {

```
margin-bottom: 23px;
}
```
# OrganiserSignUpTerms ul {

```
padding-bottom: 0;
}
```
# mc_embed_signup .button {

```
margin: 0;
}
```

/\* End of Align MailChimp form items with Divi modules */

.MonkeyRewardsButtonSmall {
    @extend .small-button;
}

.MonkeyRewardsButtonSmall: hover {
    @extend .icon-button: hover;
}

.MonkeyRewardsButtonSmall: active {
    @extend .small-button: active;
}

--- End of file ---

**Comment by DD-UX** [comment]
@EleanorEllis I think I had the same issue. Just installed the plugin and had to do a lot of things until finally realized the last slashes in the directories weren't added.

Check this screenshot and see how I've added the "closing" slashes in the end.

<img width="704" alt="screen shot 2016-10-03 at 3 33 55 pm" src="https://cloud.githubusercontent.com/assets/9665653/19048983/e318fb36-897e-11e6-853f-0fe40a401924.png">

Hope this might help!

**Comment by Xavours** [comment]
Had the same problem, found the trick in that issue :
https://github.com/ConnectThink/WP-SCSS/issues/45

To trigger the plugin, you need to reload the page you're are working on in your browser. It's odd though and it will be great to have a way to trigger it manually. But sadly the guy does not seem to be willing to give any support or updates to this project. Too bad, cause the plug in seems very useful.

**Comment by brrn** [comment]
Thanks for the comments everyone. I have merged a PR that automatically adds the trailing slashes if they're not there.

**Comment by EleanorEllis** [comment]
I have added the trailing slashes and it is still not compiling. Now my directories are
scss directory:	/wp-scss-stylesheets/scss/
css directory:	/wp-scss-stylesheets/css/

**Comment by brrn** [comment]
Are you getting any error messages? Make sure you have "Error Display" set to "Show in Header" (or check the log if it is set to "Print to Log").

Have you updated to the latest version of the plugin? If so, [this user](https://github.com/ConnectThink/WP-SCSS/issues/68) suggests re-saving the settings may help.

Do you have PHP errors enabled and WordPress debugging turned on? If so, are you getting any errors? If not, give that a shot.

You may also want to try disabling all other plugins, and changing to the default theme, to see if it may be in conflict with one of them.

**Comment by geoidesic** [comment]
Why was this closed? It doesn't seem to have been resolved. I'm getting a very similar problem – the plugin doesn't seem to do anything at all.

**Comment by garrettw** [comment]
@geoidesic Yes, it will only compile to the same file name. You can't expect it to magically know that you want `main.scss` to become `style.css`.

What I did was set the paths to `/scss/` and `/`, and my main scss file is called `style.scss` so that it compiles down to the CSS file WordPress looks for.
Also, I want to make sure you're using the correct terminology: a partial is a filename that begins with an underscore. This library will not (or at least should not) compile partials directly into individual CSS files; you'd have to `@import` them in a main SCSS file.

If what you're calling "partials" don't begin with an underscore, then you must be generating several CSS files that all have to be fetched by the **browser**. This is not ideal. The browser should only fetch one CSS file.

**Comment by aleshh** [comment]
Nope. I've got the plugin installed and activated, scss directory set to `/scss/` and css directory set to `/css/`. Made a file called `style.scss` in the scss directory with my css in it and nothing's happening. I've tried re-saving, reloading the homepage, and even adding `define('WP_SCSS_ALWAYS_RECOMPILE', true);` to functions.php. 

Bummer.

**Comment by garrettw** [comment]
Try the things mentioned by @brrn above. That's really all you can do.

**Comment by ljohanne** [comment]
This helps !
See the screen below, the message related about the missed directories passed away.
I hope this screenshot help anyone with this problem as well.

<img width="813" alt="Screen Shot 2019-05-25 at 1 43 19 PM" src="https://user-images.githubusercontent.com/32311982/58373411-79600780-7ef3-11e9-9934-69738f1acce4.png">
